agents:
  trae_agent:
    enable_lakeview: false
    model: lab_model
    max_steps: 3
    tools:
      - task_done

allow_mcp_servers: []
mcp_servers: {}

model_providers:
  anthropic:
    api_key: ""
    provider: anthropic

models:
  lab_model:
    model_provider: anthropic
    model: claude-sonnet-4-20250514
    max_tokens: 512
    temperature: 0
    top_p: 1
    top_k: 0
    max_retries: 1
    parallel_tool_calls: false
